### ISSUE TITLE
You are running a SCAM site and Hosting code on Github

### ISSUE THREAD

**Issue by thomascrha** [blueimp/aws-lambda#5]
You aren't very good at obfuscating your code are you ? All I want is my money back and I will go away, simple.

![Your Github Repo](https://i.imgur.com/0eym4Ye.png)

**Comment by blueimp** [comment]
Hello @thomascrha,

if you got scammed you should contact the police instead of harassing someone that has absolutely nothing to do with whatever happened to you.

Since you spammed on the issue tracker of several of my open source projects you should have noticed that I'm the author of a number of open source projects, some of which also have demo sites hosted on GitHub pages.
It is entirely possible - though not a good idea - that a developer includes resources from some of my demo pages in their web page, which can easily explain those domain requests you pointed out in your screenshot.

It also seems the author of the page from your screenshot used my photo (https://blueimp.net/static/profile-74fe7ba7.jpg) without my permission.
Again, I have nothing to do with this site and certainly don't approve of their usage of my picture.

The owner of the domain apparently registered it via GoDaddy, which you can find out via their [WHOIS](https://www.godaddy.com/whois) database, or simply by using the `whois` command-line program.
So I suggest you contact them about the abuse and again, should contact the police if you got scammed.

Kind regards,
Sebastian
